### ISSUE TITLE
Don't require the props.children when visibility set to false.

### ISSUE THREAD

**Issue by domino2** [marlo22/react-sticky-mouse-tooltip#6]
Hello, thanks for the package.
I've encountered with the issue when set the `visible` attribute to false along with the generated content. 
Usualy when there is not visibility attribute, I need to use the `display/visibility` property of the css or `{ !some_statement ?  null : <span>html</span> }`.

I like the idea of the visibility attribute, but I suppose that I don't need to care about the content. So I end up with
```
<MouseTooltip className="dot-tooltip" visible={activeDot !== undefined} offsetX={15} offsetY={10}>
   { activeDot === undefined ? <span></span> :
      <ul>
         <li>{ activeDot.item_name }</li>
         <li>{ activeDot.y_name }: { activeDot.y_value }</li>
         <li>{ activeDot.x_name }: { activeDot.x_value }</li>
      </ul>
   }
</MouseTooltip>
```

And in this case, there is no advantage of the visibility attribute and I can wrap the whole `MouseTooltip` to the `{ !some_statement ?  null : <span>html</span> }`.

**Comment by marlo22** [comment]
Hi @domino2 , thanks for your message.

Probably I don't understand your problem. What do you want to achieve? Something like this?

```jsx
<MouseTooltip className="dot-tooltip" visible={activeDot !== undefined} offsetX={15} offsetY={10}>
  <ul>
    <li>{ activeDot.item_name }</li>
    <li>{ activeDot.y_name }: { activeDot.y_value }</li>
    <li>{ activeDot.x_name }: { activeDot.x_value }</li>
  </ul>
</MouseTooltip>
```

**Comment by domino2** [comment]
That is exactly what I was doing, but it depends on your strategy .... I'm pointing on the fact, the when used your visible attribute I wasn't expection to do this bit `{ !some_statement ? null :` to hide the tooltip and oposite whe doing that hidding statement, I don't the visibility attribute at all ...
So I think that example you provide is the best way :) ...

**Comment by marlo22** [comment]
Sorry for the late reply, but I'm really busy last time. Why don't you just do something like this: 
```jsx
{activeDot && (
  <MouseTooltip visible className="dot-tooltip" offsetX={15} offsetY={10}>
    <ul>
      <li>{ activeDot.item_name }</li>
      <li>{ activeDot.y_name }: { activeDot.y_value }</li>
      <li>{ activeDot.x_name }: { activeDot.x_value }</li>
    </ul>
  </MouseTooltip>
)}
```

**Comment by domino2** [comment]
That is what I pointed above and it is totally fine. But then the `visible` attribute is pointless, is it not?
